-- TO RESET EVERYTHING
DROP TABLE IF EXISTS Casted CASCADE;
DROP TABLE IF EXISTS Poll CASCADE;
DROP TABLE IF EXISTS PollTopic CASCADE;
DROP TABLE IF EXISTS Citizen CASCADE;
DROP TABLE IF EXISTS Municipality CASCADE;
DROP TABLE IF EXISTS Region CASCADE;
DROP TABLe IF EXISTS NewsComment CASCADE;
DROP TABLE IF EXISTS News CASCADE;
DROP TABLE IF EXISTS CastedOpinion CASCADE;
DROP TABLE IF EXISTS SpecialRole CASCADE;